#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
WEBSITE=www.yournewmachine.com
gatsby build
gsutil mb gs://${WEBSITE}
gsutil iam ch allUsers:objectViewer gs://${WEBSITE}
gsutil cp -r ${DIR}/../public/* gs://${WEBSITE}
gsutil web set -m index.html -e 404.html gs://${WEBSITE}
